### ISSUE TITLE
document pre-requisite setup for different distros

### ISSUE THREAD

**Issue by omac777** [giovanniberti/robusta#1]
**Fedora Rawhide**

Here are the pre-requisites to get the robust-example built and running successfully on Fedora Rawhide:
```
dnf install java-latest-openjdk-demo java-latest-openjdk-devel
export JAVA_HOME=/usr/lib/jvm/java-16-openjdk-16.0.0.0.36-2.rolling.fc35.x86_64
export PATH=$JAVA_HOME/bin:$PATH
```

If all goes well, you'll have a path like this:
```
echo $PATH
/usr/lib/jvm/java-16-openjdk-16.0.0.0.36-2.rolling.fc35.x86_64/bin:/home/davidm/.cargo/bin:/home/davidm/.local/bin:/home/davidm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

Now fetch the robusta sources and build the robusta-example:
```
git clone https://github.com/giovanniberti/robusta.git
cd robusta/robusta-example
make java_run
cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
javac com/example/robusta/HelloWorld.java && RUST_BACKTRACE=full java -Djava.library.path=../target/debug com.example.robusta.HelloWorld
[1, 2, 3, 4]
3
3
```

Enjoy

**Comment by omac777** [comment]
If you don't set the correct environment variables, you'll encounter the following error:
```
javac com/example/robusta/HelloWorld.java && RUST_BACKTRACE=full java -Djava.library.path=../target/debug com.example.robusta.HelloWorld
Error: LinkageError occurred while loading main class com.example.robusta.HelloWorld
	java.lang.UnsupportedClassVersionError: com/example/robusta/HelloWorld has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by omac777** [comment]
On 4/8/21 4:48 PM, Giovanni Berti wrote:
> Thanks for the issue!
> 
> Yes, `javac` and `java` should be on your PATH in order to run the examples, I'll add this prerequisite in the README.
> 
> I did try to reproduce it the issue `docker` by pulling the `fedora:rawhide`, but I couldn't:
> ```
> $ dnf install make cargo git java-latest-openjdk-demo java-latest-openjdk-devel
>  -- snip --
> $ echo $PATH
> /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> $ git clone https://github.com/giovanniberti/robusta.git
> -- snip --
> $ cd robusta/robusta-example/
> $ make java_run
> -- snip --
> javac com/example/robusta/HelloWorld.java && RUST_BACKTRACE=full java -Djava.library.path=../target/debug com.example.robusta.HelloWorld
> [1, 2, 3, 4]
> 3
> 3
> ```
> 
> The second message you posted makes me suspect that you had a Java 11 installation (which the `java` command pointed to) alongside the Java 16 installation (from which `javac` was invoked), thus causing a `UnsupportedClassVersionError`.
> 
> Could you perhaps investigate whether that's the case?
> 
Yes I do have a java 11 installation in fact there are a few java
installations and I suspect that I am like other linux users that have
older versions still installed and haven't removed those packages for
whatever their reasons like legacy production compatibility or simply
never got around to it.

That's why I felt it important mentioning this bug.  Cheers.

**Comment by giovanniberti** [comment]
Understood. I added a section in the README about running the example (7e989e0), I hope that will be enough!

Thank you for taking the time to open an issue about it :smiley:
