### ISSUE TITLE
Why is  SIG_TYPE for `()` set to "Ljava/lang/Object;"?

### ISSUE THREAD

**Issue by richox** [giovanniberti/robusta#8]
```
 impl Signature for () {
     const SIG_TYPE: &'static str = "Ljava/lang/Object;";
 }
```

if i don't understand wrong, `()` is equivalent to `void` in java. so should it be
```
 impl Signature for () {
    const SIG_TYPE: &'static str = "V";
}
```
? i tested some java functions like `void org.apache.hadoop.fs.FSDataInputStream#seek(Path path);` robusta-jni-0.2 reports error about function not found. after changing signature type for `()` to "V" it works.

**Comment by giovanniberti** [comment]
Welp, you're definitely right!

**Comment by Nthily** [comment]
Hi @giovanniberti , This issue is not fixed in the latest version, can you release a new version?  🤔
